global using Domain.Common;
global using Domain.Entities;
global using FluentValidation;
global using Application.DTOs;
global using System.Linq.Expressions;
global using Application.Extensions.ResultPattern;
global using Application.Extensions.Responses.PagedResponse;
global using Application.Contracts.Repositories.BaseRepository;
global using Application.Contracts.Repositories.BaseRepository.Crud;
